services:
  # Orion is the context broker
  orion:
    image: fiware/orion-ld
    hostname: orion
    container_name: fiware-orion-ld
    depends_on:
      - mongo-db
    expose:
      - "1026"
    ports:
      - "1026:1026" 
    command: -dbhost mongo-db -logLevel DEBUG
    healthcheck:
      test: curl --fail -s http://orion:1027/version || exit 1

  # Cygnus NGSI-LD for historical data storage
  cygnus:
    image: fiware/cygnus-ngsi-ld
    hostname: cygnus
    container_name: fiware-cygnus
    depends_on:
      - mongo-db
      - orion
    expose:
      - "5080"
    ports:
      - "5080:5080"
    environment:
      - CYGNUS_MONGO_HOSTS=mongo-db:27017
      - CYGNUS_MONGO_PORT=27017
      - CYGNUS_MONGO_DATA_DB=cygnus_data
      - CYGNUS_MONGO_ATTR_NATIVE_TYPE=false
      - CYGNUS_LOG_LEVEL=DEBUG
      - CYGNUS_API_PORT=5080
      - CYGNUS_NGSILD_CB_HOST=orion
      - CYGNUS_NGSILD_CB_PORT=1026

  # Databases
  mongo-db:
    image: mongo:3.6
    hostname: mongo-db
    container_name: db-mongo
    expose:
      - "27017"
    ports:
      - "27017:27017" 
    command: --nojournal
    volumes:
      - mongo-db:/data

  # IoT Agent
  iot-agent:
    image: fiware/iotagent-ul
    hostname: iot-agent
    container_name: fiware-iot-agent
    depends_on:
      - mongo-db
    expose:
      - "4061"
      - "7896"
    ports:
      - "4061:4061"
      - "7896:7896"
    environment:
      - "IOTA_CB_HOST=orion"
      - "IOTA_CB_PORT=1026"
      - "IOTA_NORTH_PORT=4061"
      - "IOTA_REGISTRY_TYPE=mongodb"
      - "IOTA_MONGO_HOST=mongo-db"
      - "IOTA_MONGO_PORT=27017"
      - "IOTA_MONGO_DB=iotagent-ul"
      - "IOTA_HTTP_PORT=7896"
      - "IOTA_PROVIDER_URL=http://iot-agent:4061"
      
volumes:
  mongo-db: ~
