services:
  # Orion is the context broker
  orion:
    image: fiware/orion-ld
    hostname: orion
    container_name: fiware-orion-ld
    depends_on:
      - mongo-db
    expose:
      - "1026"
    ports:
      - "1026:1026" 
    command: -dbhost mongo-db -logLevel DEBUG
    environment:
      - ORION_LOG_LEVEL=DEBUG
    healthcheck:
      test: curl --fail -s http://orion:1027/version || exit 1

  # IoT Agent for devices
  #iot-agent:
  #  image: fiware/iotagent-ul
  #  hostname: iot-agent
  #  container_name: fiware-iot-agent
  #  depends_on:
  #    - mongo-db
  #    - orion
  #  expose:
  #    - "4061"
  #    - "7896"
  #  ports:
  #    - "4061:4061"
  #    - "7896:7896"
  #  environment:
  #    - "IOTA_CB_HOST=orion"
  #    - "IOTA_CB_PORT=1026"
  #    - "IOTA_NORTH_PORT=4061"
  #    - "IOTA_REGISTRY_TYPE=mongodb"
  #    - "IOTA_MONGO_HOST=mongo-db"
  #    - "IOTA_MONGO_PORT=27017"
  #    - "IOTA_MONGO_DB=iotagent-ul"
  #    - "IOTA_HTTP_PORT=7896"
  #    - "IOTA_PROVIDER_URL=http://iot-agent:4061"
    
  # MongoDB for device data
  mongo-db:
    image: mongo:3.6
    hostname: mongo-db
    container_name: db-mongo
    expose:
      - "27017"
    ports:
      - "27017:27017" 
    command: --nojournal
    volumes:
      - mongo-db:/data

volumes:
  mongo-db: ~
  timescale-data: ~